// Brand typefaces, self-hosted via @fontsource (no Google CDN request) so
// they load offline — important for the file:// `ship/` deliverable. Family
// names match the design tokens (Rajdhani / IBM Plex Sans / IBM Plex Mono).
import '@fontsource/rajdhani/latin-600.css';
import '@fontsource/rajdhani/latin-700.css';
import '@fontsource/ibm-plex-sans/latin-400.css';
import '@fontsource/ibm-plex-sans/latin-500.css';
import '@fontsource/ibm-plex-sans/latin-700.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import '@fontsource/ibm-plex-mono/latin-700.css';

// Design-language tokens (single source of truth — generated by the
// design tier in `design/language/theme.css`). Imported by relative path
// because the design system lives outside `src/`.
import '../design/language/theme.css';
import '@/shared/styles/reset.css';
import 'react-toastify/dist/ReactToastify.css';

import { createRoot } from 'react-dom/client';

import App from './App';

const container = document.getElementById('root');
if (!container) throw new Error('Root element not found');

createRoot(container).render(<App />);
